# Fine-tuning + EWC on NetHack.
# §4 / App. B.1: "For EWC we use a regularization coefficient of 2 * 10^6"
env: nethack
character: "mon-hum-neu-mal"
algo: appo
total_steps: 500_000_000
retention: ewc
ewc_lambda: 2.0e6
ewc_apply_to_critic: false # App. C.5
fisher_n_batches: 10000 # Addendum: 10 000 batches from NLD-AA
fisher_dataset: nld_aa
load_pretrained: true
freeze_encoders: true
freeze_baseline_pretrain_steps: 500_000_000
disable_entropy_bonus: true
hidden_dim: 1738
batch_size: 128
unroll_length: 32
discounting: 0.999999
appo_clip_policy: 0.1
appo_clip_baseline: 1.0
adam_learning_rate: 1.0e-4
weight_decay: 1.0e-4
adam_eps: 1.0e-7
grad_norm_clipping: 4
baseline_cost: 1.0
entropy_cost: 0.0
reward_clip: 10
reward_scale: 1.0
